let builtins: [Symbol: IntermediateValue] = [
    Symbol("+"): .callable(.addFunction),
    Symbol("/"): .callable(.divideFunction),
    Symbol("*"): .callable(.multiplyFunction),
    Symbol("-"): .callable(.subtractFunction),
    Symbol(">"): .callable(.gtFunction),
    Symbol(">="): .callable(.gteFunction),
    Symbol("<"): .callable(.ltFunction),
    Symbol("<="): .callable(.lteFunction),
    Symbol("concat"): .callable(.concatFunction),
    Symbol("define"): .callable(.defineFunction),
    Symbol("eq"): .callable(.eqFunction),
    Symbol("filter"): .callable(.filterFunction),
    Symbol("fn"): .callable(.fnFunction),
    Symbol("if"): .callable(.ifFunction),
    Symbol("is-nil"): .callable(.isNilFunction),
    Symbol("len"): .callable(.lenFunction),
    Symbol("let"): .callable(.letFunction),
    Symbol("map"): .callable(.mapFunction),
    Symbol("merge"): .callable(.mergeFunction),
    Symbol("not"): .callable(.notFunction),
    Symbol("sub"): .callable(.subFunction),
]
